### ISSUE TITLE
Can't copy page from one site group to another

### ISSUE THREAD

**Issue by Zmove** [OFFLINE-GmbH/oc-boxes-support#166] opened 2024-12-11 12:27 UTC
**Describe the bug**
When you use the "Copy to another site / language" feature, it works well when  you copy the page to another site of the same group, but it doesn't work when you want to copy the page to a site that is in another group.

**Boxes Version**
v3.6.37

**To Reproduce**
1. Create several site group, and several websites for each group
2. Create some pages in one site
3. Try to copy the page to another website of another site group by using the "Copy to another site / language" button and choosing the other site in the popup
4. You should get redirected to the other site, but the page was not copied, you are in the home of boxes editor

**Screenshots**

https://www.loom.com/share/aeefa220a6de4491a10871ce750ccb9c

**Additional context**
In my setup, each site have it's own subtheme that depend on a parent theme. Encountered no problem with that setup yet, but it can be an important precision if you can't reproduce the bug in a single theme context.

**Comment by tobias-kuendig** [comment] 2024-12-11 12:46
@Zmove thank you for the report. Do you see the page copied in the database? Is a new row added but assigned to the wrong site?

**Comment by Zmove** [comment] 2024-12-11 12:57
Not easy to say, I'm on sqlite on shared hosting and can't use my standard tool to open .sqlite file as it create too much process for that shared host and I get kicked from ssh connection.

If you have you own playground I think you will be able to reproduce and get the info you want faster than me, otherwise I have to copy the site to a localhost to get access to my database datas

**Comment by tobias-kuendig** [comment] 2024-12-12 07:59
Thank you @Zmove, it was indeed a problem with child themes in a multi site context.

This is fixed in v3.6.38, let me know if you experience any further problems!

**Comment by Zmove** [comment] 2024-12-12 18:30
Hello @tobias-kuendig. I made the update and tried to copy my page to another site, I have the exact same problem.

My setup is 4 site group, 8 sites (french and english for each site group), what I try is to copy from site 1 > fr to site 2 > fr.
- Site 1 - FR have site1 theme
- Site 1 - EN have site1 theme
- Site 2 - FR have site2 theme
- Site 2 - EN have site2 theme

All that themes are child theme of a master theme.

The behavior is exactly the same than in the loom video. If you need I can send you a mail with BO and FTP access to check.

**Edit : Important précision : The copy between Site 1 - FR to Site 1 - EN works, so it seems to be related to the fact that I have several sites groups.**

Thank you

**Comment by tobias-kuendig** [comment] 2024-12-13 07:17
@Zmove would you mind sending me the `offline_boxes_*` and `system_site_*` tables?

I currently cannot reproduce the issue on my end.

**Comment by tobias-kuendig** [comment] 2024-12-13 12:45
@Zmove thank you very much! I was able to reproduce the issue with your DB dump.

Since you copied pages to another site with the faulty version of Boxes, you now have pages in your DB where the `theme` value is wrong (like IDs 23, 25 and 26). You can delete these pages from the database or simply set the correct `theme` and they will appear in the backend editor.

Starting from version v3.6.42, the site-specific (child) theme is considered when copying pages, so it should work know (even if you did not clean up your DB first).

**Closed as completed by tobias-kuendig** 2024-12-13 12:45 UTC
Labels: bug

**Comment by Zmove** [comment] 2024-12-13 12:56
I confirm it works, thank you very much @tobias-kuendig
