### ISSUE TITLE
Hidden for nav nested Boxes pages are shown in Static Menu

### ISSUE THREAD

**Issue by anastasiauz** [OFFLINE-GmbH/oc-boxes-support#117] opened 2024-04-10 18:18 UTC
**Describe the bug**
Nested items are excluded from navigation when the Page 'is_hidden'==1 but not when 'is_hidden_in_navigation'==1 
/plugins/offline/boxes/classes/traits/HasMenuItems.php, 
notice line 122: "'viewBag' => ['isHidden' => (bool)$child->is_hidden]", publishing the whole function here:

```php    
    public static function iterateChildMenuItems($currentUrl, ?bool $allowNesting = true): Closure
    {
        $iterator = function (\October\Rain\Database\Collection $children) use (
            &$iterator,
            $currentUrl,
            $allowNesting
        ) {
            $branch = [];

            foreach ($children as $child) {
                $pageUrl = URL::to($child->url);
                $item = [
                    'url' => $pageUrl,
                    'title' => $child->name,
                    'isActive' => $pageUrl === $currentUrl,
                    'viewBag' => ['isHidden' => (bool)$child->is_hidden],
                ];

                if ($allowNesting && $child->children->count() > 0) {
                    $item['items'] = $iterator($child->children);
                }

                $branch[] = $item;
            }

            return $branch;
        };

        // Make sure php-cs-fixer does not strip out the $iterator variable.
        // It is used as a reference in the closure above.
        $_ = $iterator;

        return $iterator;
    }
```

**Boxes Version**
latest, paid

**To Reproduce**
1. Create Static menu, choose a box page which has some children
2. Hide one of children from navigation
3. Output children with "allow children" and "replace item with its children"
4. See the hidden for nav item shown in menu

Please add this condition as we would like to build the menu based on boxes pages tree and this feature of excluding from nav is very nice. Thank you!

**Comment by tobias-kuendig** [comment] 2024-04-11 16:38
@anastasiauz thank you for this report! Can you confirm that the issue is fixed in v3.5.13? Also, if you use revisions, make sure to view the page in a private window or properly publish the pages to weed out any issues with the revisioning system.

**Comment by anastasiauz** [comment] 2024-04-12 07:00
In my case I'm adding all children of a subpage and the child is indeed hiding only if on line 122 of /plugins/offline/boxes/classes/traits/HasMenuItems.php both checks are present:
`'viewBag' => ['isHidden' => (bool)$child->is_hidden || (bool)$child->is_hidden_in_navigation],`

So currently the hidden for nav page is hidden when all boxes pages are added (the whole tree) but not if children of some page. Not sure why but this fix solves it.

As always - thank you for answering and fixing things really fast!

**Comment by tobias-kuendig** [comment] 2024-04-13 09:14
Great, thank you!

**Closed as completed by tobias-kuendig** 2024-04-13 09:14 UTC
Labels: bug
